import * as React from "react"
import { InfoIcon, SparklesIcon, TriangleAlertIcon, UserRoundIcon } from "lucide-react"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/registry/medcn/lib/utils"
import { Avatar, AvatarFallback } from "@/registry/medcn/avatar/avatar"
import { Badge } from "@/registry/medcn/badge/badge"

export type AiMessageRole = "user" | "assistant" | "system"
export type AiMessageState = "draft" | "streaming" | "complete" | "error"

const aiMessageVariants = cva("group/message flex gap-2.5", {
  variants: {
    role: {
      user: "flex-row-reverse",
      assistant: "",
      system: "",
    },
  },
  defaultVariants: {
    role: "assistant",
  },
})

const bubbleVariants = cva(
  "min-w-0 max-w-[85%] rounded-xl px-3.5 py-2.5 text-sm leading-relaxed",
  {
    variants: {
      role: {
        user: "bg-primary text-primary-foreground",
        assistant: "bg-muted text-foreground",
        system:
          "bg-info/8 text-foreground border-info/25 max-w-full border text-[13px]",
      },
      state: {
        draft: "opacity-80",
        streaming: "",
        complete: "",
        error: "border-destructive/40 bg-destructive/8 text-foreground border",
      },
    },
    defaultVariants: {
      role: "assistant",
      state: "complete",
    },
  }
)

export interface AiMessageProps
  extends Omit<React.ComponentProps<"article">, "role" | "content">,
    VariantProps<typeof aiMessageVariants> {
  state?: AiMessageState
  /** Overrides the default avatar for the role. */
  avatar?: React.ReactNode
  /** Author label. Defaults from the role. */
  author?: React.ReactNode
  /** Timestamp or model/version metadata, shown beside the author. */
  metadata?: React.ReactNode
  /**
   * Show the "Generated" badge on assistant content. On by default — turn it off
   * only where the surrounding product already establishes provenance.
   */
  showGeneratedLabel?: boolean
  /** Attachment cards, rendered above the content. */
  attachments?: React.ReactNode
  /** Citations / evidence, rendered under the content. */
  citations?: React.ReactNode
  /** Action row, rendered under the citations. */
  actions?: React.ReactNode
}

const ROLE_ICONS: Record<AiMessageRole, React.ElementType> = {
  user: UserRoundIcon,
  assistant: SparklesIcon,
  system: InfoIcon,
}

const ROLE_AUTHORS: Record<AiMessageRole, string> = {
  user: "You",
  assistant: "Assistant",
  system: "System",
}

/**
 * One turn in a clinical assistant transcript. Assistant content is labelled as
 * generated by default so it is never mistaken for authored clinical
 * documentation, and an errored turn stays in the transcript rather than
 * disappearing.
 */
function AiMessage({
  className,
  role = "assistant",
  state = "complete",
  avatar,
  author,
  metadata,
  showGeneratedLabel = true,
  attachments,
  citations,
  actions,
  children,
  ...props
}: AiMessageProps) {
  const resolvedRole: AiMessageRole = role ?? "assistant"
  const Icon = ROLE_ICONS[resolvedRole]
  const isAssistant = resolvedRole === "assistant"

  return (
    <article
      data-slot="ai-message"
      data-role={resolvedRole}
      data-state={state}
      className={cn(aiMessageVariants({ role }), className)}
      {...props}
    >
      {avatar ?? (
        <Avatar size="sm" className="mt-0.5 shrink-0">
          <AvatarFallback
            className={cn(
              isAssistant && "bg-primary/12 text-primary",
              resolvedRole === "system" && "bg-info/12 text-info"
            )}
          >
            <Icon className="size-3.5" aria-hidden />
          </AvatarFallback>
        </Avatar>
      )}

      <div
        className={cn(
          "flex min-w-0 flex-col gap-1.5",
          resolvedRole === "user" ? "items-end" : "items-start"
        )}
      >
        <div className="text-muted-foreground flex flex-wrap items-center gap-2 px-0.5 text-[11px]">
          <span className="font-semibold">
            {author ?? ROLE_AUTHORS[resolvedRole]}
          </span>

          {isAssistant && showGeneratedLabel && (
            <Badge
              variant="soft"
              className="h-4 px-1.5 py-0 text-[10px] font-semibold"
            >
              Generated
            </Badge>
          )}

          {state === "draft" && (
            <Badge
              variant="outline"
              className="h-4 px-1.5 py-0 text-[10px] font-semibold"
            >
              Draft
            </Badge>
          )}

          {state === "error" && (
            <span className="text-destructive inline-flex items-center gap-1 font-semibold">
              <TriangleAlertIcon className="size-3" aria-hidden />
              Failed
            </span>
          )}

          {metadata}
        </div>

        {attachments && (
          <div data-slot="ai-message-attachments" className="flex flex-wrap gap-2">
            {attachments}
          </div>
        )}

        <div
          data-slot="ai-message-content"
          className={cn(bubbleVariants({ role, state }))}
        >
          {children}
          {state === "streaming" && (
            <>
              <span
                aria-hidden
                className="bg-foreground/70 ml-0.5 inline-block h-3.5 w-0.5 translate-y-0.5 motion-safe:animate-pulse"
              />
              <span className="sr-only">Response in progress</span>
            </>
          )}
        </div>

        {citations && (
          <div data-slot="ai-message-citations" className="px-0.5">
            {citations}
          </div>
        )}

        {actions && <div data-slot="ai-message-actions-slot">{actions}</div>}
      </div>
    </article>
  )
}

export { AiMessage, aiMessageVariants }
