"use client"

import * as React from "react"

import { cn } from "@/registry/medcn/lib/utils"
import { Label } from "@/registry/medcn/label/label"

export interface FieldProps
  extends Omit<React.ComponentProps<"div">, "children"> {
  /** Field label text. */
  label?: React.ReactNode
  /** Muted helper text under the control. Hidden while an error is shown. */
  description?: React.ReactNode
  /** Error message; also marks the control aria-invalid. */
  error?: React.ReactNode
  /** Marks the label with a required asterisk. */
  required?: boolean
  /** Explicit id for the control; autogenerated otherwise. */
  htmlFor?: string
  /**
   * The form control. A single element child gets `id`, `aria-describedby`
   * and `aria-invalid` wired automatically; a render function receives them.
   */
  children:
    | React.ReactElement
    | ((controlProps: {
        id: string
        "aria-describedby": string | undefined
        "aria-invalid": boolean | undefined
      }) => React.ReactNode)
}

/** Label + control + description/error wrapper with a11y wiring. */
function Field({
  className,
  label,
  description,
  error,
  required = false,
  htmlFor,
  children,
  ...props
}: FieldProps) {
  const autoId = React.useId()
  const id = htmlFor ?? autoId
  const descriptionId = `${id}-description`
  const errorId = `${id}-error`
  const describedBy = error ? errorId : description ? descriptionId : undefined

  const controlProps = {
    id,
    "aria-describedby": describedBy,
    "aria-invalid": error ? true : undefined,
  }

  return (
    <div
      data-slot="field"
      data-invalid={error ? true : undefined}
      className={cn("grid w-full gap-2", className)}
      {...props}
    >
      {label != null && (
        <Label htmlFor={id}>
          {label}
          {required && (
            <span aria-hidden="true" className="text-destructive">
              *
            </span>
          )}
        </Label>
      )}
      {typeof children === "function"
        ? children(controlProps)
        : React.cloneElement(
            children as React.ReactElement<Record<string, unknown>>,
            controlProps
          )}
      {error ? (
        <p
          id={errorId}
          data-slot="field-error"
          className="text-destructive text-xs font-medium"
        >
          {error}
        </p>
      ) : description != null ? (
        <p
          id={descriptionId}
          data-slot="field-description"
          className="text-muted-foreground text-xs"
        >
          {description}
        </p>
      ) : null}
    </div>
  )
}

export { Field }
